chunking:
  method: sentence         # line, sentence, paragraph, header, custom
  max_tokens: 100
  overlap_tokens: 10
  inject_headers: true

embedding:
  provider: voyage         # openai or huggingface or ollama (not supported)
  model: voyage-3-large