chunking:
  method: paragraph         # line, sentence, paragraph, header, custom
  max_tokens: 300
  overlap_tokens: 40
  inject_headers: true

embedding:
  provider: voyage         # openai or huggingface or ollama (not supported)
  model: voyage-3-large