chunking:
  method: sentence         # line, sentence, paragraph, header, custom
  max_tokens: 100
  overlap_tokens: 10
  inject_headers: true

embedding:
  provider: openai         # openai or huggingface or ollama (not supported)
  model: text-embedding-3-small